/// Flutter icons IconHelp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconHelp
///      fonts:
///       - asset: fonts/IconHelp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconHelp {
  IconHelp._();

  static const _kFontFam = 'IconHelp';
  static const String? _kFontPkg = null;

  static const IconData iconhelp = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
