/// Flutter icons IconLanguage
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconLanguage
///      fonts:
///       - asset: fonts/IconLanguage.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconLanguage {
  IconLanguage._();

  static const _kFontFam = 'IconLanguage';
  static const String? _kFontPkg = null;

  static const IconData icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
