/// Flutter icons IconLogout
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconLogout
///      fonts:
///       - asset: fonts/IconLogout.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconLogout {
  IconLogout._();

  static const _kFontFam = 'IconLogout';
  static const String? _kFontPkg = null;

  static const IconData icon__1_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
