/// Flutter icons IconPassword
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPassword
///      fonts:
///       - asset: fonts/IconPassword.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPassword {
  IconPassword._();

  static const _kFontFam = 'IconPassword';
  static const String? _kFontPkg = null;

  static const IconData icon__2_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
